### ISSUE TITLE
Not all headings appear in the Quarto table of contents

### ISSUE THREAD

**Issue by daslu** [scicloj/clay#100]
This is probably a Quarto problem. We mention it here first, and may open a Quarto issue after learning the situation a little more.

Following [a report](https://clojurians.slack.com/archives/C0BQDEJ8M/p1714951475216919) of `jason1903` in Slack, we see the following.
(using Quarto version 1.5.10 pre-release)

The following Quarto document:
```qmd
---
format:
  html:
    toc: true
---

# A

## AB

### ABC
```
renders as follows (not showing `ABC` in the table of contents):
![image](https://github.com/scicloj/clay/assets/5673102/503a9eb2-e6c1-47f4-ae80-97e719adff0c)

**Comment by genmeblog** [comment]
What about setting `toc-depth 3`?

**Comment by daslu** [comment]
Updating following the [the Slack thread](https://clojurians.slack.com/archives/C0BQDEJ8M/p1714951475216919):

* Some of the problems I experienced (e.g. the one above) were not because the toc items were hidden, but because they were collapsed (and then can be expended when scrolling to the relevant region in the page). `:toc-expand 4` makes sure they are expanded by default.

* There is another problem that happens when mixing markdown headings and inline html headings, as Jason commented in Slack. 

E.g., 
```quote
# One Hash

## Two Hashes

### Three Hashes As Clj Comment

### Three Hashes In `kind/md`

```{=html}
<div><h3>An H3 In `kind/hiccup`</h3></div>
```

This is simply not supposed to be handled by Quarto, as discussed here:
https://github.com/quarto-dev/quarto-cli/issues/9738

Many thanks to Jason and the Quarto devs for clarifying this.
