### ISSUE TITLE
Git clone failure (early EOF)

### ISSUE THREAD

**Issue by whatacold** [scicloj/clay#159]
Hi,

It's weird that I can't clone this repo in the command line, even a shallow one: `git clone --depth 1 -vv https://github.com/scicloj/clay.git`. The error looks like below and I've tried it many times:

```
Cloning into 'clay'...
POST git-upload-pack (175 bytes)
want 8d07656ff14f4582b162c612de8227148c1ec18b (HEAD)
want 8d07656ff14f4582b162c612de8227148c1ec18b (refs/heads/main)
POST git-upload-pack (229 bytes)
remote: Enumerating objects: 863, done.
remote: Counting objects: 100% (863/863), done.
remote: Compressing objects: 100% (447/447), done.
error: 7450 bytes of body are still expected | 38.00 KiB/s 
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

I'm not sure if there are some git settings are not ok on my side, but I can clone other repos correctly as always.

**Comment by daslu** [comment]
Thanks for reporting.  Strange.

I could not reproduce this.

**Comment by whatacold** [comment]
Okay, never mind, then it’s more likely a problem on my side, I’ll look
into it.
