### ISSUE TITLE
Example setup fails due to missing dependency 

### ISSUE THREAD

**Issue by mchughs** [scicloj/clay#166]
System: Linux + VSCode + Calva

Steps to reproduce:
1. Start a REPL on the `clay/examples/example-project` directory.
2. This will install some dependencies. You can check which by running `clj -Stree` from your terminal with this project as root.
3. Confirm that any reference to the tablecloth library is **not** present.
4. With your REPL, eval the `example1` ns and try running the `(require '[scicloj.clay.v2.api :as clay])` expression in the comment block
5. You should get the following error in your output.
```clj
; Execution error (FileNotFoundException) at scicloj.clay.v2.server/eval9126$loading (server.clj:1).
; Could not locate tablecloth/api__init.class, tablecloth/api.clj or tablecloth/api.cljc on classpath.
```  

Possible fix:
Adding `scicloj/tablecloth {:mvn/version "RELEASE"}` to the `deps` fixes this issue. Though maybe the deeper problem is that tablecloth should be a subdependency of Clay

**Comment by daslu** [comment]
Thanks, this will be fixed in the coming release thanks to #162.
