### ISSUE TITLE
without deps.edn (i.e. only clj -$deps ...), :live-reload does not work

### ISSUE THREAD

**Issue by kloimhardt** [scicloj/clay#176]
I tried with Java (Temurin) 21 and Java 23
```
$ clj -Sdeps "{:deps {org.scicloj/clay {:mvn/version \"2-beta21\"}}}"
Clojure 1.11.1
user=> (require '[scicloj.clay.v2.api :as clay])
nil
user=> (clay/make! {:source-path "lambert.clj"})
serving Clay at http://localhost:1971/
[[[[:wrote "docs/lambert.html"] nil]] nil [:watching-new-files #{}]]
user=> (clay/make! {:source-path "lambert.clj" :live-reload true})
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Execution error (NullPointerException) at java.util.Objects/requireNonNull (Objects.java:220).
null
user=> (clay/make! {:source-path "lambert.clj" :live-reload true})
Execution error (NullPointerException) at java.util.Objects/requireNonNull (Objects.java:220).
null
user=>
```

**Comment by daslu** [comment]
Thanks!

Zulip discussion:
https://clojurians.zulipchat.com/#narrow/channel/422115-clay-dev/topic/.3Alive-reload

**Comment by whatacold** [comment]
Thanks for the report! I'll look into it if I have some time at hand.

**Comment by whatacold** [comment]
Hi @kloimhardt Unfortunately, I can't reproduce the problem, it works as expected on my side.

Did you have an error stacktrace for the exception?

**Comment by kloimhardt** [comment]
@whatacold thank you so much for taking the time and doing this. I guess 99% of people will start with a deps.edn. Mine is just an artificial edge case, a consciously chosen minimal setup. The idea is a setup for the busy Python scientist who is willing to give Clay a try using notepad++. But maybe it is only an idee fixe of mine, and all is well the way it is.

**Comment by whatacold** [comment]
@kloimhardt Hi Markus, I just fixed this issue and created a PR, would you love to verify if it fixes the problem on your side? Thanks!
