### ISSUE TITLE
Emacs/Cider clays snippet in docs maybe creates error

### ISSUE THREAD

**Issue by ezmiller** [scicloj/clay#18]
I haven't yet had time to look into it fully, but I think the Emacs/Cider snippet that helps send the result of code evaluation to the tools causes cider jack-in to fail when loading a project that does not have clay as a dependency.

I think it is ammending the jack-in command for all subsequent projects, adding clay as a dependency. 

https://scicloj.github.io/clay/#CIDER

**Comment by daslu** [comment]
closing (it was relevant to the old setup that involved an alias and nrepl-middleware)
