### ISSUE TITLE
Missing the direct value visualization functionality

### ISSUE THREAD

**Issue by egri-nagy** [scicloj/clay#25]
Around alpha38 I used ```handle-value!``` to display graphs generated on the fly to display them in the browser, like
```
  (clay/start!)
  (clay/handle-value! (create-game-report raw title))
```
As of alpha42, it seems the assumption is that a notebook already is in a file - examples all seem to specify source-path.

Is there still a way to render a value (just a vega-lite diagram, or a table, or a hiccup document) without storing it in a file first?

**Comment by daslu** [comment]
Version `2-alpha47` is worth trying for the code snippet above.

**Comment by egri-nagy** [comment]
Yes, I can confirm that ```2-alpha49``` works fine. Thanks a lot!

**Comment by daslu** [comment]
Thanks!
