### ISSUE TITLE
HTML wrap for Quarto

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clay#54]
Wrap HTML into a code block with `{=html}` to allow `data-qmd` attribute being interpreted by Quarto.

https://quarto.org/docs/authoring/tables.html#html-output

Also, prepare a function which wrap any result into such `span` or `div` 

More: https://clojurians.zulipchat.com/#narrow/stream/422115-clay-dev/topic/formatting.20tables/near/419446284

**Comment by daslu** [comment]
fixed on `"2-alpha78"`
